export default {
  'url': 'URL',
  'tag': 'Tag',
  'name': 'Name',
  'add': 'Add',
  'all': 'All',
  'addBookmark': 'Add bookmark',
  'addChannel': 'Add channel',
  'settings': 'Settings',
  'youtubeChannelOrPlaylist': 'Youtube channel or playlist',
  'empty': 'Empty',
  'noBookmarksFound': 'No bookmarks found',
  'noChannelsFound': 'No channels found',
  'noVideosFound': 'No videos found',
  'noConfigFound': 'No config found',
  'general': 'General',
  'channels': 'Channels',
  'bookmarks': 'Bookmarks',
  'remove': 'Remove',
  'restore': 'Restore',
  'instance': 'Instance',
  'instanceId': 'settings-instance',
  'feedReload': 'Reload feed after (minutes)',
  'feedReloadId': 'settings-reload-feed-after',
  'feedLimit': 'Number of videos in feed',
  'feedLimitId': 'settings-number-of-videos-in-feed',
  'saveHint': 'Press Enter to save changes',
  'notFound': 'Not found',
  'back': 'Back',
  'searchForChannel': 'Search for channel',
  'sync': 'Synchronize',
  'menu': 'Menu'
}
