export default {
  'url': 'URL',
  'tag': 'Tag',
  'name': 'Name',
  'add': 'Add',
  'all': 'All',
  'addBookmark': 'Add bookmark',
  'addChannel': 'Add channel',
  'settings': 'Settings',
  'youtubeChannelOrPlaylist': 'Youtube channel or playlist',
  'empty': 'Empty',
  'noBookmarksFound': 'No bookmarks found',
  'noChannelsFound': 'No channels found',
  'noVideosFound': 'No videos found',
  'noConfigFound': 'No config found',
  'general': 'General',
  'channels': 'Channels',
  'bookmarks': 'Bookmarks',
  'remove': 'Remove',
  'restore': 'Restore',
  'instance': 'Instance',
  'instanceId': 'settings-instance',
  'cache': 'Cache (in minutes)',
  'cacheId': 'settings-cache',
  'saveHint': 'Press Enter to save changes'
}
